/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdcprojectgui;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luke
 */
public class GUI extends java.awt.Frame
{

    public CardLayout cards;
    public ArrayList<JButton> qButtons;
    public Game thisGame;
    public ArrayList<JButton> btnLifelines;
    
    /**
     * Creates new form GUI
     */
    public GUI()
    {
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension screenSize = kit.getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;
        int windowHeight = screenHeight/2;
        int windowWidth = screenWidth/2;
        
        this.setTitle("Who Wants to be a Millionaire!");
        this.setLocation(windowWidth/2,windowHeight/2);
        this.setResizable(false);
        
        initComponents();
        cards = (CardLayout) pnlCardHolder.getLayout();
        qButtons = new ArrayList<JButton>();
        qButtons.add(btnAnswer1);
        qButtons.add(btnAnswer2);
        qButtons.add(btnAnswer3);
        qButtons.add(btnAnswer4);
        
        btnLifelines = new ArrayList<JButton>();
        btnLifelines.add(btnATA);
        btnLifelines.add(btnPAF);
        btnLifelines.add(btnFF);
        
        DefaultTableModel model=new DefaultTableModel()
        {
        @Override
            public boolean isCellEditable(int i, int i1) 
            {
                return false;
            }
        };
        
        jTable1.setModel(model);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setCellSelectionEnabled(false);
        
    }
    
    public void setGame(Game current)
    {
        thisGame = current;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlCardHolder = new javax.swing.JPanel();
        crdStartScreen = new javax.swing.JPanel();
        javax.swing.JLabel lblWelcome = new javax.swing.JLabel();
        btnViewScoreboard = new javax.swing.JButton();
        btnStart1 = new javax.swing.JButton();
        btnStartScrnQuit = new javax.swing.JButton();
        pnlQuestionScreen = new javax.swing.JPanel();
        pnlAnswerButtons = new javax.swing.JPanel();
        btnAnswer1 = new javax.swing.JButton();
        btnAnswer2 = new javax.swing.JButton();
        btnAnswer3 = new javax.swing.JButton();
        btnAnswer4 = new javax.swing.JButton();
        pnlQuestionDisplay = new javax.swing.JPanel();
        lblForPrize = new javax.swing.JLabel();
        pnlLLButtons = new javax.swing.JPanel();
        lblQuestion = new javax.swing.JLabel();
        btnATA = new javax.swing.JButton();
        btnFF = new javax.swing.JButton();
        btnPAF = new javax.swing.JButton();
        btnWalkAway = new javax.swing.JButton();
        pnlScoreboard = new javax.swing.JPanel();
        lblScore = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlQuitPlayAgain = new javax.swing.JPanel();
        btnQuit = new javax.swing.JButton();
        btnPlayAgain = new javax.swing.JButton();
        pnlSaveScore = new javax.swing.JPanel();
        lblEndMessage = new javax.swing.JLabel();
        pnlScoreQuestion = new javax.swing.JPanel();
        lblSaveScore = new javax.swing.JLabel();
        btnSaveYes = new javax.swing.JButton();
        btnQuitNoScore = new javax.swing.JButton();
        btnQuitViewScores = new javax.swing.JButton();
        btnBacktoMenu = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCardHolder.setLayout(new java.awt.CardLayout());

        crdStartScreen.setMinimumSize(new java.awt.Dimension(883, 528));
        crdStartScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome to Who Wants to be a Millionaire!");
        crdStartScreen.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 880, -1));

        btnViewScoreboard.setText("View High Scores");
        btnViewScoreboard.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnViewScoreboardActionPerformed(evt);
            }
        });
        crdStartScreen.add(btnViewScoreboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 220, -1));

        btnStart1.setText("Start");
        btnStart1.setMaximumSize(new java.awt.Dimension(133, 32));
        btnStart1.setMinimumSize(new java.awt.Dimension(133, 32));
        btnStart1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStart1ActionPerformed(evt);
            }
        });
        crdStartScreen.add(btnStart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, -1));

        btnStartScrnQuit.setText("Quit");
        btnStartScrnQuit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnQuitNoScoreActionPerformed(evt);
            }
        });
        crdStartScreen.add(btnStartScrnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 220, -1));

        pnlCardHolder.add(crdStartScreen, "card2");

        pnlAnswerButtons.setLayout(new java.awt.GridLayout(2, 2));

        btnAnswer1.setText("Default Answer 1");
        btnAnswer1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAnswerActionPerformed(evt);
            }
        });
        pnlAnswerButtons.add(btnAnswer1);

        btnAnswer2.setText("Default Answer 2");
        btnAnswer2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAnswerActionPerformed(evt);
            }
        });
        pnlAnswerButtons.add(btnAnswer2);

        btnAnswer3.setText("Default Answer 3");
        btnAnswer3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAnswerActionPerformed(evt);
            }
        });
        pnlAnswerButtons.add(btnAnswer3);

        btnAnswer4.setText("Default Answer 4");
        btnAnswer4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAnswerActionPerformed(evt);
            }
        });
        pnlAnswerButtons.add(btnAnswer4);

        pnlQuestionDisplay.setLayout(new java.awt.GridLayout(2, 1));

        lblForPrize.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        lblForPrize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForPrize.setText("For $example");
        pnlQuestionDisplay.add(lblForPrize);

        pnlLLButtons.setLayout(new java.awt.GridLayout(1, 0));

        lblQuestion.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuestion.setText("Default Question ONE?");
        pnlLLButtons.add(lblQuestion);

        pnlQuestionDisplay.add(pnlLLButtons);

        btnATA.setText("Ask The Audience");
        btnATA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lifelineActionPerformed(evt);
            }
        });

        btnFF.setText("50/50");
        btnFF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lifelineActionPerformed(evt);
            }
        });

        btnPAF.setText("Phone a Friend");
        btnPAF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lifelineActionPerformed(evt);
            }
        });

        btnWalkAway.setText("Walk Away");
        btnWalkAway.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lifelineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuestionScreenLayout = new javax.swing.GroupLayout(pnlQuestionScreen);
        pnlQuestionScreen.setLayout(pnlQuestionScreenLayout);
        pnlQuestionScreenLayout.setHorizontalGroup(
            pnlQuestionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAnswerButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlQuestionScreenLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(btnATA)
                .addGap(0, 0, 0)
                .addComponent(btnFF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPAF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnWalkAway, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuestionScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlQuestionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlQuestionScreenLayout.setVerticalGroup(
            pnlQuestionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestionScreenLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlQuestionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnATA)
                    .addComponent(btnFF)
                    .addComponent(btnPAF)
                    .addComponent(btnWalkAway))
                .addGap(18, 18, 18)
                .addComponent(pnlQuestionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlAnswerButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlCardHolder.add(pnlQuestionScreen, "card3");

        pnlScoreboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScore.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("Score Board");
        lblScore.setToolTipText("");
        lblScore.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblScore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblScore.setPreferredSize(new java.awt.Dimension(228, 80));
        pnlScoreboard.add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 880, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(20, 0));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 265));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jTable1.setToolTipText("");
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setMinimumSize(new java.awt.Dimension(45, 0));
        jTable1.setRowMargin(2);
        jTable1.setShowVerticalLines(false);
        jTable1.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0)
        {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(2);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        pnlScoreboard.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 820, 270));

        pnlQuitPlayAgain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnQuit.setText("Quit");
        btnQuit.setDefaultCapable(false);
        btnQuit.setFocusable(false);
        btnQuit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnQuit.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnQuit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnQuitActionPerformed(evt);
            }
        });
        pnlQuitPlayAgain.add(btnQuit);

        btnPlayAgain.setText("Back to Main Menu");
        btnPlayAgain.setDefaultCapable(false);
        btnPlayAgain.setFocusable(false);
        btnPlayAgain.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnPlayAgain.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPlayAgainActionPerformed(evt);
            }
        });
        pnlQuitPlayAgain.add(btnPlayAgain);

        pnlScoreboard.add(pnlQuitPlayAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 880, 90));

        pnlCardHolder.add(pnlScoreboard, "card4");

        pnlSaveScore.setLayout(new java.awt.GridLayout(2, 1));

        lblEndMessage.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblEndMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEndMessage.setText("end message here");
        pnlSaveScore.add(lblEndMessage);

        pnlScoreQuestion.setLayout(new java.awt.GridBagLayout());

        lblSaveScore.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblSaveScore.setText("Save your score?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        pnlScoreQuestion.add(lblSaveScore, gridBagConstraints);

        btnSaveYes.setText("Yes");
        btnSaveYes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSaveYesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        pnlScoreQuestion.add(btnSaveYes, gridBagConstraints);

        btnQuitNoScore.setText("No, just quit");
        btnQuitNoScore.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnQuitNoScoreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        pnlScoreQuestion.add(btnQuitNoScore, gridBagConstraints);

        btnQuitViewScores.setText("No, view score board");
        btnQuitViewScores.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnQuitViewScoresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        pnlScoreQuestion.add(btnQuitViewScores, gridBagConstraints);

        btnBacktoMenu.setText("Back to Main Menu");
        btnBacktoMenu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBacktoMenuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        pnlScoreQuestion.add(btnBacktoMenu, gridBagConstraints);

        pnlSaveScore.add(pnlScoreQuestion);

        pnlCardHolder.add(pnlSaveScore, "card5");

        add(pnlCardHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 882, 527));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btnViewScoreboardActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnViewScoreboardActionPerformed
    {//GEN-HEADEREND:event_btnViewScoreboardActionPerformed
        // TODO add your handling code here:
        cards.show(pnlCardHolder, "card4");
    }//GEN-LAST:event_btnViewScoreboardActionPerformed

    private void btnStart1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStart1ActionPerformed
    {//GEN-HEADEREND:event_btnStart1ActionPerformed

        cards.show(pnlCardHolder, "card3");  
    }//GEN-LAST:event_btnStart1ActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnQuitActionPerformed
    {//GEN-HEADEREND:event_btnQuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnAnswerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAnswerActionPerformed
    {//GEN-HEADEREND:event_btnAnswerActionPerformed
        int answer = -1;
        if(evt.getSource() == btnAnswer1)
        {
           answer = 1; 
        }
        else if(evt.getSource() == btnAnswer2)
        {
            answer = 2;
        }
        else if(evt.getSource() == btnAnswer3)
        {
            answer = 3;
        }
        else if(evt.getSource() == btnAnswer4)
        {
            answer = 4;
        }
        
        thisGame.checkAnswer(answer);
    }//GEN-LAST:event_btnAnswerActionPerformed

    private void lifelineActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lifelineActionPerformed
    {//GEN-HEADEREND:event_lifelineActionPerformed
        char lifelineType = '-';
        JButton source = (JButton)evt.getSource();
        if(source == btnATA)
        {
            lifelineType = 'A';
            source.setEnabled(false);
        }
        else if(source == btnPAF)
        {
            lifelineType = 'P';
            source.setEnabled(false);
        }
        else if(source == btnFF)
        {
            lifelineType = 'F';
            source.setEnabled(false);
        }
        else if(source == btnWalkAway)
        {
            lifelineType = 'W';
        }
        
        thisGame.useLifeLine(lifelineType);
    }//GEN-LAST:event_lifelineActionPerformed

    private void btnQuitViewScoresActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnQuitViewScoresActionPerformed
    {//GEN-HEADEREND:event_btnQuitViewScoresActionPerformed
        cards.show(pnlCardHolder, "card4");
    }//GEN-LAST:event_btnQuitViewScoresActionPerformed

    private void btnQuitNoScoreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnQuitNoScoreActionPerformed
    {//GEN-HEADEREND:event_btnQuitNoScoreActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnQuitNoScoreActionPerformed

    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPlayAgainActionPerformed
    {//GEN-HEADEREND:event_btnPlayAgainActionPerformed
        thisGame.resetGame();
        cards.show(pnlCardHolder, "card2");
    }//GEN-LAST:event_btnPlayAgainActionPerformed

    private void btnBacktoMenuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBacktoMenuActionPerformed
    {//GEN-HEADEREND:event_btnBacktoMenuActionPerformed
        thisGame.resetGame();
        cards.show(pnlCardHolder, "card2");
    }//GEN-LAST:event_btnBacktoMenuActionPerformed

    private void btnSaveYesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveYesActionPerformed
    {//GEN-HEADEREND:event_btnSaveYesActionPerformed
        thisGame.saveScore();
        cards.show(pnlCardHolder, "card4");
    }//GEN-LAST:event_btnSaveYesActionPerformed

    public void changeCard(String cardName)
    {
        cards.show(pnlCardHolder, cardName);
    }
   
    public void setQuestionText(String text)
    {
        lblQuestion.setText(text);
    }
    
    public void setPrize(String prize)
    {
        lblForPrize.setText(prize);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnATA;
    private javax.swing.JButton btnAnswer1;
    private javax.swing.JButton btnAnswer2;
    private javax.swing.JButton btnAnswer3;
    private javax.swing.JButton btnAnswer4;
    private javax.swing.JButton btnBacktoMenu;
    private javax.swing.JButton btnFF;
    private javax.swing.JButton btnPAF;
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnQuitNoScore;
    private javax.swing.JButton btnQuitViewScores;
    private javax.swing.JButton btnSaveYes;
    private javax.swing.JButton btnStart1;
    private javax.swing.JButton btnStartScrnQuit;
    private javax.swing.JButton btnViewScoreboard;
    private javax.swing.JButton btnWalkAway;
    private javax.swing.JPanel crdStartScreen;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JLabel lblEndMessage;
    private javax.swing.JLabel lblForPrize;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblSaveScore;
    private javax.swing.JLabel lblScore;
    private javax.swing.JPanel pnlAnswerButtons;
    private javax.swing.JPanel pnlCardHolder;
    private javax.swing.JPanel pnlLLButtons;
    private javax.swing.JPanel pnlQuestionDisplay;
    private javax.swing.JPanel pnlQuestionScreen;
    private javax.swing.JPanel pnlQuitPlayAgain;
    private javax.swing.JPanel pnlSaveScore;
    private javax.swing.JPanel pnlScoreQuestion;
    private javax.swing.JPanel pnlScoreboard;
    // End of variables declaration//GEN-END:variables
}
